const ScreenNames = {
  DashHome: 'DashHome',
  Home: 'Home',
  OnBoarding: 'OnBoarding',
  Login: 'Login',
  SignUp: 'SignUp',
  ForgotPassword: 'ForgotPassword',
  ResetPassword: 'ResetPassword',
  Search: 'Search',
  stories: 'stories',
  carts: 'carts',
  profile: 'profile',
  wishlist: 'wishlist',
  contactus: 'contactus',
  privacypolicy: 'privacyPolicy',
  returnpolicy: 'returnpolicy',
  feedback: 'feedback',
  purchaseGiftCard: 'purchaseGiftCard',
  customerSupport: 'customerSupport',
  refundPolicy: 'refundPolicy',
  reward: 'reward',
  termsAndConditions: 'termsAndConditions',
  aboutus: 'aboutus',
  shippingpolicy: 'shippingpolicy',
  productList: 'productList',
  accessories: 'accessories',
  productdetails: 'productdetails',
};

export default ScreenNames;
